version: '3.9'

services:
  djangoapi:
    container_name: djangoapi
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapi:/djangoapi
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:15-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env_files/.env